// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.apache.shenyu.examples.tars.servant.testapp;

import com.qq.tars.protocol.annotation.Servant;
import com.qq.tars.protocol.tars.annotation.TarsMethodParameter;

@Servant
public interface HelloServant {

    String hello(@TarsMethodParameter(name = "no") int no, @TarsMethodParameter(name = "name") String name);

    int helloInt(@TarsMethodParameter(name = "no") int no, @TarsMethodParameter(name = "name") String name);

}
