/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.apache.shenyu.examples.tars.servant.testapp;

import com.qq.tars.protocol.annotation.Servant;
import com.qq.tars.protocol.tars.annotation.TarsMethodParameter;

@Servant
public interface UserServant {
    
    /**
     * Test hello for tar.
     * @param no  a param with name no
     * @param name  a param with name name
     * @return result
     */
    String hello(@TarsMethodParameter(name = "no") int no, @TarsMethodParameter(name = "name") String name);

    /**
     * Test hello int for tar.
     * @param no  a param with name no
     * @param name  a param with name name
     * @return result
     */
    int helloInt(@TarsMethodParameter(name = "no") int no, @TarsMethodParameter(name = "name") String name);

}
