# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shenyu-admin-master
  labels:
    app: shenyu-admin-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shenyu-admin-master
  template:
    metadata:
      labels:
        app: shenyu-admin-master
    spec:
      containers:
        - name: shenyu-admin-master
          image: apache/shenyu-admin:latest
          args:
            - -Xmx768m -Xms768m
          env:
            - name: 'TZ'
              value: 'Asia/Beijing'
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: server.port
              value: "9095"
            - name: shenyu.cluster.enabled
              value: "true"
            - name: shenyu.sync.websocket.allowOrigins
              value: ws://localhost:9095;ws://localhost:9195;
            - name: shenyu.cluster.type
              value: "zookeeper"
            - name: shenyu.cluster.zookeeper.url
              value: "shenyu-zookeeper:2181"
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              value: shenyue2e
            - name: spring.datasource.url
              value: jdbc:mysql://shenyu-mysql:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9095
              path: /actuator/health
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9095
              path: /actuator/health
          ports:
            - containerPort: 9095
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mysql-connector-volume
              mountPath: /opt/shenyu-admin/ext-lib
      volumes:
        - name: mysql-connector-volume
          hostPath:
            path: /tmp/shenyu-e2e/mysql/driver
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shenyu-admin-slave
  labels:
    app: shenyu-admin-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shenyu-admin-slave
  template:
    metadata:
      labels:
        app: shenyu-admin-slave
    spec:
      containers:
        - name: shenyu-admin-slave
          image: apache/shenyu-admin:latest
          args:
            - -Xmx768m -Xms768m
          env:
            - name: 'TZ'
              value: 'Asia/Beijing'
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: server.port
              value: "9096"
            - name: shenyu.cluster.enabled
              value: "true"
            - name: shenyu.sync.websocket.allowOrigins
              value: ws://localhost:9096;ws://localhost:9195;
            - name: shenyu.cluster.type
              value: "zookeeper"
            - name: shenyu.cluster.zookeeper.url
              value: "shenyu-zookeeper:2181"
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              value: shenyue2e
            - name: spring.datasource.url
              value: jdbc:mysql://shenyu-mysql:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9096
              path: /actuator/health
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9096
              path: /actuator/health
          ports:
            - containerPort: 9096
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mysql-connector-volume
              mountPath: /opt/shenyu-admin/ext-lib
      volumes:
        - name: mysql-connector-volume
          hostPath:
            path: /tmp/shenyu-e2e/mysql/driver
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shenyu-bootstrap-cluster
  labels:
    app: shenyu-bootstrap-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shenyu-bootstrap-cluster
  template:
    metadata:
      labels:
        app: shenyu-bootstrap-cluster
    spec:
      containers:
        - name: shenyu-bootstrap-cluster
          image: apache/shenyu-bootstrap:latest
          resources: { }
          args:
            - -Xmx768m -Xms768m
          env:
            - name: shenyu.sync.websocket.urls
              value: ws://shenyu-admin-master:9095/websocket,ws://shenyu-admin-slave:9096/websocket
          ports:
            - containerPort: 9195
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9195
              path: /actuator/health
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9195
              path: /actuator/health
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: shenyu-admin-master
  labels:
    app: shenyu-admin-master
spec:
  type: NodePort
  selector:
    app: shenyu-admin-master
  ports:
    - name: "9095"
      port: 9095
      targetPort: 9095
      nodePort: 31095

---
apiVersion: v1
kind: Service
metadata:
  name: shenyu-admin-slave
  labels:
    app: shenyu-admin-slave
spec:
  type: NodePort
  selector:
    app: shenyu-admin-slave
  ports:
    - name: "9096"
      port: 9096
      targetPort: 9096
      nodePort: 31096

---
apiVersion: v1
kind: Service
metadata:
  name: shenyu-bootstrap-cluster
  labels:
    app: shenyu-bootstrap-cluster
spec:
  type: NodePort
  selector:
    app: shenyu-bootstrap-cluster
  ports:
    - name: "9195"
      port: 9195
      targetPort: 9195
      nodePort: 31195