# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


services:
  shenyu-zk:
    container_name: shenyu-zk
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    networks:
      - shenyu

  shenyu-kafka:
    container_name: shenyu-kafka
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - shenyu-zk
    networks:
      - shenyu
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "shenyu-zk:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      listeners: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://shenyu-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  shenyu-examples-http:
    deploy:
      resources:
        limits:
          memory: 2048M
    container_name: shenyu-examples-http
    image: shenyu-examples-http:latest
    restart: always
    environment:
      - shenyu.register.serverLists=http://shenyu-admin:9095
    healthcheck:
      test: [ "CMD", "wget", "http://shenyu-examples-http:8189/test/path/123?name=tom" ]
      timeout: 2s
      retries: 30
    ports:
      - "31189:8189"
    networks:
      - shenyu

networks:
  shenyu:
    name: shenyu
    driver: bridge
    external: true