#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### shengyu getway proxy findById
POST http://localhost:9195/sofa/findById
Accept: application/json
Content-Type: application/json

{
  "id": "123"
}

### shengyu getway proxy findAll
GET http://localhost:9195/sofa/findAll
Accept: application/json


### shengyu getway proxy insert
POST http://localhost:9195/sofa/insert
Accept: application/json
Content-Type: application/json

{
  "id": 123,
  "name": "test"
}

### shengyu getway proxy findByIdsAndName
GET http://localhost:9195/sofa/findByIdsAndName
Accept: application/json
Content-Type: application/json

{
  "ids": [
    123,
    124,
    125
  ],
  "name": "test"
}

### shengyu getway proxy findByArrayIdsAndName
GET http://localhost:9195/sofa/findByArrayIdsAndName
Accept: application/json
Content-Type: application/json

{
  "ids": [
    123,
    124,
    125
  ],
  "name": "test"
}

### shengyu getway proxy findByStringArray
GET http://localhost:9195/sofa/findByStringArray
Accept: application/json
Content-Type: application/json

{
  "ids": [
    123,
    124,
    125
  ]
}

### shengyu getway proxy findByListId
GET http://localhost:9195/sofa/findByListId
Accept: application/json
Content-Type: application/json

{
  "ids": [
    123,
    124,
    125
  ]
}

### shengyu getway proxy batchSave
PUT http://localhost:9195/sofa/batchSave
Accept: application/json
Content-Type: application/json

{
  "sofaTestList": [
    {
      "id": "123",
      "name": "test"
    },
    {
      "id": "123",
      "name": "test"
    },
    {
      "id": "123",
      "name": "test"
    }
  ]
}

### shengyu getway proxy batchSaveNameAndId
PUT http://localhost:9195/sofa/batchSaveNameAndId
Accept: application/json
Content-Type: application/json

{
  "sofaTestList": [
    {
      "id": "123",
      "name": "test"
    },
    {
      "id": "123",
      "name": "test"
    },
    {
      "id": "123",
      "name": "test"
    }
  ],
  "id": "123",
  "name": "test"
}

### shengyu getway proxy saveComplexBean
PUT http://localhost:9195/sofa/saveComplexBean
Accept: application/json
Content-Type: application/json

{
  "sofaSimpleTypeBean": {
    "id": "123",
    "name": "test"
  },
  "idLists": [
    123,
    124
  ],
  "idMaps": {
    "abc": "abc",
    "cbd": "cbd"
  }
}

### shengyu getway proxy saveComplexBeanAndName
PUT http://localhost:9195/sofa/saveComplexBeanAndName
Accept: application/json
Content-Type: application/json

{
  "sofaComplexTypeBean": {
    "sofaSimpleTypeBean": {
      "id": "123",
      "name": "test"
    },
    "idLists": [
      123,
      124
    ],
    "idMaps": {
      "abc": "abc",
      "cbd": "cbd"
    }
  },
  "name": "name"
}

### shengyu getway proxy saveTwoList
PUT http://localhost:9195/sofa/saveTwoList
Accept: application/json
Content-Type: application/json

{
  "sofaComplexTypeBeanList": [
    {
      "sofaSimpleTypeBean": {
        "id": "123",
        "name": "test"
      },
      "idLists": [
        123,
        124
      ],
      "idMaps": {
        "abc": "abc",
        "cbd": "cbd"
      }
    }
  ],
  "testKey1": {
    "id": "123",
    "name": "test"
  },
  "testKey2": {
    "id": "123",
    "name": "test"
  }
}
