#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


### shengyu alibaba dubbo /sdk/dubbo/findAll
GET http://localhost:8899/sdk/dubbo/findAll
Accept: application/json
Content-Type: application/json

### shengyu alibaba dubbo /sdk/dubbo/findList
GET http://localhost:8899/sdk/dubbo/findList
Accept: application/json
Content-Type: application/json

### shengyu alibaba dubbo /sdk/dubbo/findById
GET http://localhost:8899/sdk/dubbo/findById?id=1
Accept: application/json
Content-Type: application/json

### shengyu alibaba dubbo /sdk/dubbo/findByListId
POST http://localhost:8899/sdk/dubbo/findByListId
Accept: application/json
Content-Type: application/json
{
    "ids":["1","2"]
}

### shengyu alibaba dubbo /sdk/dubbo/insert
POST http://localhost:8899/sdk/dubbo/insert
Accept: application/json
Content-Type: application/json
{
    "id":1L,
    "name":"helloworld"
}

### shengyu alibaba dubbo /sdk/dubbo/findByIdsAndName
POST http://localhost:8899/sdk/dubbo/findByIdsAndName
Accept: application/json
Content-Type: application/json
{
    "ids":["1","2"],
    "name":"333"
}

### shengyu alibaba dubbo /sdk/dubbo/findByArrayIdsAndName
POST http://localhost:8899/sdk/dubbo/findByArrayIdsAndName
Accept: application/json
Content-Type: application/json
{
    "ids":[1,12],
    "name":"999"
}

### shengyu alibaba dubbo /sdk/dubbo/saveComplexBeanTest
POST http://localhost:8899/sdk/dubbo/saveComplexBeanTest
Accept: application/json
Content-Type: application/json
{
    "dubboTest":{
        "id": "123",
        "name": "test1"
    },
    "idLists": [
        "1",
        "2"
    ],
    "idMaps": {
  }
}

### shengyu alibaba dubbo /sdk/dubbo/batchSave
POST http://localhost:8899/sdk/dubbo/batchSave
Accept: application/json
Content-Type: application/json
{
    "dubboTestList": [
        {
            "name": "22222",
            "id": "122"
        }
    ]
}

### shengyu alibaba dubbo /sdk/dubbo/batchSaveAndNameAndId
POST http://localhost:8899/sdk/dubbo/batchSaveAndNameAndId
Accept: application/json
Content-Type: application/json
{
    "dubboTestList": [
        {
            "name": "22222",
            "id": "122"
        }
    ],
    "id":"123344",
    "name":"testete"
}


