# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shenyu-admin-h2
  labels:
    app: shenyu-admin-h2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shenyu-admin-h2
  template:
    metadata:
      labels:
        app: shenyu-admin-h2
    spec:
      containers:
        - name: shenyu-admin-h2
          image: apache/shenyu-admin:latest
          resources: {
            limits: { cpu: "1", memory: "1324Mi" },
            requests: { cpu: "0.5", memory: "1024Mi" }
          }
          args:
            - -Xmx768m -Xms768m
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: h2
            - name: shenyu.database.init_script
              value: sql-script/h2/schema.sql
          ports:
            - containerPort: 9095
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9095
              path: /actuator/health
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9095
              path: /actuator/health
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shenyu-bootstrap-h2
  labels:
    app: shenyu-bootstrap-h2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shenyu-bootstrap-h2
  template:
    metadata:
      labels:
        app: shenyu-bootstrap-h2
    spec:
#      initContainers:
#        - name: shenyu-bootstrap-h2-init
#          image: busybox
#          command: ['sh', '-c', 'until nslookup shenyu-admin-h2; do echo waiting for shenyu-admin-h2; sleep 2; done;']
      containers:
        - name: shenyu-bootstrap-h2
          image: apache/shenyu-bootstrap:latest
          resources: {}
          args:
            - -Xmx768m -Xms768m
          env:
            - name: shenyu.sync.websocket.urls
              value: ws://shenyu-admin-h2:9095/websocket
          ports:
            - containerPort: 9195
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9195
              path: /actuator/health
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 9195
              path: /actuator/health
      restartPolicy: Always
