/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package org.apache.shenyu.protocol.grpc.message;

/**
 * JsonProto.
 */
public final class JsonProto {

    static final com.google.protobuf.Descriptors.Descriptor INTERNAL_STATIC_JSON_REQUEST_DESCRIPTOR;

    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable INTERNAL_STATIC_JSON_REQUEST_FIELD_ACCESSOR_TABLE;

    static final com.google.protobuf.Descriptors.Descriptor INTERNAL_STATIC_JSON_REPLY_DESCRIPTOR;

    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable INTERNAL_STATIC_JSON_REPLY_FIELD_ACCESSOR_TABLE;

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    private JsonProto() {
    }

    /**
     * getDescriptor.
     *
     * @return descriptor
     */
    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        String[] descriptorData = {"\n\njson.proto\"\036\n\013JsonRequest\022\017\n\007message\030\001"
                + " \001(\t\"\034\n\tJsonReply\022\017\n\007message\030\001 \001(\tB6\n\'or"
                + "g.apache.shenyu.protocol.grpc.messageB\tJ"
                + "sonProtoP\001b\006proto3",
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{});

        INTERNAL_STATIC_JSON_REQUEST_DESCRIPTOR = getDescriptor().getMessageTypes().get(0);

        INTERNAL_STATIC_JSON_REQUEST_FIELD_ACCESSOR_TABLE = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(INTERNAL_STATIC_JSON_REQUEST_DESCRIPTOR, new String[]{"Message", });

        INTERNAL_STATIC_JSON_REPLY_DESCRIPTOR = getDescriptor().getMessageTypes().get(1);

        INTERNAL_STATIC_JSON_REPLY_FIELD_ACCESSOR_TABLE = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(INTERNAL_STATIC_JSON_REPLY_DESCRIPTOR, new String[]{"Message", });
    }

    /**
     * registerAllExtensions.
     *
     * @param registry registry
     */
    public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * registerAllExtensions.
     *
     * @param registry registry
     */
    public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

}
