/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package org.apache.shenyu.protocol.grpc.message;

/**
 * Protobuf type {@code JsonRequest}.
 */
public final class JsonRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:JsonRequest)
        JsonRequestOrBuilder {

    public static final int MESSAGE_FIELD_NUMBER = 1;

    private static final long serialVersionUID = 0L;

    private static final com.google.protobuf.Parser<JsonRequest> PARSER = new com.google.protobuf.AbstractParser<JsonRequest>() {
        @Override
        public JsonRequest parsePartialFrom(final com.google.protobuf.CodedInputStream input,
                                            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new JsonRequest(input, extensionRegistry);
        }
    };

    // @@protoc_insertion_point(class_scope:JsonRequest)
    private static final JsonRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new JsonRequest();
    }

    private volatile Object message;

    private byte memoizedIsInitialized = -1;

    // Use JsonRequest.newBuilder() to construct.
    private JsonRequest(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private JsonRequest() {
        message = "";
    }

    private JsonRequest(final com.google.protobuf.CodedInputStream input,
                        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10:
                        String s = input.readStringRequireUtf8();

                        message = s;
                        break;

                    default:
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;

                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    @Override
    @SuppressWarnings("unused")
    protected Object newInstance(final UnusedPrivateParameter unused) {
        return new JsonRequest();
    }

    @Override
    public com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    /**
     * getDescriptor.
     *
     * @return Descriptors.Descriptor
     */
    public static com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return JsonProto.INTERNAL_STATIC_JSON_REQUEST_DESCRIPTOR;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
        return JsonProto.INTERNAL_STATIC_JSON_REQUEST_FIELD_ACCESSOR_TABLE
                .ensureFieldAccessorsInitialized(
                        JsonRequest.class, Builder.class);
    }

    /**
     * <code>string message = 1;</code>.
     *
     * @return The message.
     */
    @Override
    public String getMessage() {
        Object ref = message;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            message = s;
            return s;
        }
    }

    /**
     * <code>string message = 1;</code>.
     *
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString getMessageBytes() {
        Object ref = message;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            message = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    @Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(final com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getMessageBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (!getMessageBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof JsonRequest)) {
            return super.equals(obj);
        }
        JsonRequest other = (JsonRequest) obj;

        if (!getMessage().equals(other.getMessage())) {
            return false;
        }
        return unknownFields.equals(other.unknownFields);
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @Override
    protected Builder newBuilderForType(final BuilderParent parent) {
        return new Builder(parent);
    }

    /**
     * newBuilder.
     *
     * @return Builder
     */
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    /**
     * getDefaultInstance.
     *
     * @return JsonRequest
     */
    public static JsonRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    @Override
    public com.google.protobuf.Parser<JsonRequest> getParserForType() {
        return PARSER;
    }

    @Override
    public JsonRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code JsonRequest}.
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:JsonRequest)
            JsonRequestOrBuilder {
        private Object message = "";

        // Construct using org.apache.shenyu.protocol.grpc.message.JsonRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(final BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return JsonProto.INTERNAL_STATIC_JSON_REQUEST_FIELD_ACCESSOR_TABLE
                    .ensureFieldAccessorsInitialized(
                            JsonRequest.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
        }

        @Override
        public Builder clear() {
            super.clear();
            message = "";

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return JsonProto.INTERNAL_STATIC_JSON_REQUEST_DESCRIPTOR;
        }

        @Override
        public JsonRequest getDefaultInstanceForType() {
            return JsonRequest.getDefaultInstance();
        }

        @Override
        public JsonRequest build() {
            JsonRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public JsonRequest buildPartial() {
            JsonRequest result = new JsonRequest(this);
            result.message = message;
            onBuilt();
            return result;
        }

        @Override
        public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field,
                                final Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
                                        final int index,
                                        final Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
                                        final Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(final com.google.protobuf.Message other) {
            if (other instanceof JsonRequest) {
                return mergeFrom((JsonRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        @Override
        public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
                                 final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            JsonRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (JsonRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * mergeFrom.
         *
         * @param other other
         * @return Builder
         */
        public Builder mergeFrom(final JsonRequest other) {
            if (other == JsonRequest.getDefaultInstance()) {
                return this;
            }
            if (!other.getMessage().isEmpty()) {
                message = other.message;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public boolean isInitialized() {
            return true;
        }

        /**
         * <code>string message = 1;</code>.
         *
         * @return The message.
         */
        public String getMessage() {
            Object ref = message;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string message = 1;</code>.
         *
         * @return The bytes for message.
         */
        public com.google.protobuf.ByteString getMessageBytes() {
            Object ref = message;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string message = 1;</code>.
         *
         * @param value The message to set.
         * @return This builder for chaining.
         */
        public Builder setMessage(final String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            message = value;
            onChanged();
            return this;
        }

        /**
         * <code>string message = 1;</code>.
         *
         * @return This builder for chaining.
         */
        public Builder clearMessage() {
            message = getDefaultInstance().getMessage();
            onChanged();
            return this;
        }

        /**
         * <code>string message = 1;</code>.
         *
         * @param value The bytes for message to set.
         * @return This builder for chaining.
         */
        public Builder setMessageBytes(final com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            message = value;
            onChanged();
            return this;
        }

        @Override
        public Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
    }
}
