# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.8'

services:
  shenyu-zookeeper:
    image: zookeeper:3.5
    container_name: shenyu-zookeeper
    ports:
      - "2181:2181"  # Client
      - "2888:2888"  # Server
      - "3888:3888"  # Leader election
      - "8080:8080"  # Website
    healthcheck:
      test: [ "CMD-SHELL", "echo srvr | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: always
    networks:
      - shenyu
  shenyu-examples-sofa:
    image: shenyu-examples-sofa:latest
    container_name: shenyu-examples-sofa
    environment:
      - shenyu.register.serverLists=http://shenyu-admin:9095
      - sofa.boot.rpc.registry.address=zookeeper://shenyu-zookeeper:2181
    ports:
      - "30811:8011"
      - "20888:20888"
    restart: always
    depends_on:
      shenyu-zookeeper:
        condition: service_healthy
    networks:
      - shenyu

networks:
  shenyu:
    name: shenyu
    driver: bridge
    external: true
