# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shenyu-examples-eureka
  labels:
    app: shenyu-examples-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shenyu-examples-eureka
  strategy: {}
  template:
    metadata:
      labels:
        app: shenyu-examples-eureka
    spec:
      containers:
        - image: shenyu-examples-eureka:latest
          name: shenyu-examples-eureka
          livenessProbe:
            httpGet:
              port: 8761
              path: /actuator/health
#            exec:
#              command:
#                - wget -q -O - http://localhost:8761/actuator/health | grep UP || exit 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: eureka.instance.client.serviceUrl.defaultZone
              value: http://shenyu-examples-eureka:8761
          ports:
            - containerPort: 8761
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: shenyu-examples-eureka
spec:
  type: NodePort
  selector:
    app: shenyu-examples-eureka
  ports:
    - name: "8761"
      protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30761
