# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#apiVersion: v1
#kind: Namespace
#metadata:
#  name: shenyu
#  labels:
#    name: shenyu
#---

apiVersion: v1
kind: ConfigMap
metadata:
  name: shenyu-configmap
  labels:
    app: shenyu-configmap
data:
  shenyu-admin-application.yml: |
    server:
      port: 9095
      address: 0.0.0.0
    
    spring:
      profiles:
        active: h2
      thymeleaf:
        cache: true
        encoding: utf-8
        enabled: true
        prefix: classpath:/static/
        suffix: .html
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
      jackson:
        time-zone: GMT+8 # GMT , Asia/Shanghai
      messages:
        basename: message/i18n
    
    
    management:
      health:
        mail:
          enabled: off
      endpoints:
        web:
          exposure:
            include:
              - 'health'
              - 'prometheus'
        enabled-by-default: true
    
    mybatis:
      config-location: classpath:/mybatis/mybatis-config.xml
      mapper-locations: classpath:/mappers/*.xml
      type-handlers-package: org.apache.shenyu.admin.mybatis.handler
    
    shenyu:
      register:
        registerType: http #http #zookeeper #etcd #nacos #consul
        serverLists: #localhost:2181 #http://localhost:2379 #localhost:8848
        props:
          sessionTimeout: 5000
          connectionTimeout: 2000
          checked: true
          zombieCheckThreads: 10
          zombieCheckTimes: 5
          scheduledTime: 10
          nacosNameSpace: ShenyuRegisterCenter
      ldap:
        enabled: false
        url: ldap://xxxx:xxx
        bind-dn: cn=xxx,dc=xxx,dc=xxx
        password: xxxx
        base-dn: ou=xxx,dc=xxx,dc=xxx
        object-class: person
        login-field: cn
      jwt:
        expired-seconds: 86400000
      shiro:
        white-list:
          - /
          - /favicon.*
          - /static/**
          - /index**
          - /platform/login
          - /websocket
          - /error
          - /actuator/health
          - /actuator/health/** # /actuator/health/readiness /actuator/health/liveness
          - /actuator/prometheus
          - /swagger-ui.html
          - /swagger-ui/**
          - /webjars/**
          - /v3/api-docs/**
          - /csrf
          - /alert/report
      dashboard:
        core:
          onlySuperAdminPermission:
            - system:manager:add
            - system:manager:edit
            - system:manager:delete
            - system:role:add
            - system:role:edit
            - system:role:delete
            - system:resource:addButton
            - system:resource:addMenu
            - system:resource:editButton
            - system:resource:editMenu
            - system:resource:deleteButton
            - system:resource:deleteMenu
    
    springdoc:
      api-docs:
        enabled: true
      swagger-ui:
        enabled: true
        tags-sorter: alpha
      packages-to-scan: org.apache.shenyu.admin.controller
      paths-to-match: /**
    
    logging:
      level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.apache.shenyu.bonuspoint: info
        org.apache.shenyu.lottery: info
        org.apache.shenyu: info
    #    org.apache.shenyu.admin.utils.HttpUtils: debug
    

  shenyu-admin-application-mysql.yml: |
    shenyu:
      database:
        dialect: mysql
        init_enable: true

    spring:
      datasource:
        url: jdbc:mysql://shenyu-mysql:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        username: root
        password: shenyue2e
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          connection-timeout: 30000
          minimum-idle: 5
          maximum-pool-size: 20
          auto-commit: true
          idle-timeout: 600000
          max-lifetime: 1800000
          connection-test-query: SELECT 1
          connection-init-sql: SET NAMES utf8mb4
          validation-timeout: 800
      mail:
        # Attention: this is mail server address.
        host: smtp.qq.com
        username: shenyu@apache.com
        # Attention: this is not email account password, this requires an email authorization code
        password: your-password
        #Attention: Tencent mail smtps 465,smtp 587
        port: 587
        properties:
          mail:
            smtp:
              socketFactoryClass: javax.net.ssl.SSLSocketFactory
              ssl:
                enable: true

  shenyu-bootstrap-application.yml: |
    server:
      port: 9195
      address: 0.0.0.0
      compression:
        enabled: true
        minResponseSize: 1MB # If the response data is greater than 1MB, enable compression.

    spring:
      main:
        allow-bean-definition-overriding: true
      application:
        name: shenyu-bootstrap
      codec:
        max-in-memory-size: 2MB
      cloud:
        discovery:
          enabled: true
        nacos:
          discovery:
            server-addr: 127.0.0.1:8848 # Spring Cloud Alibaba Dubbo use this.
            enabled: false
            namespace: ShenyuRegisterCenter

    # if you want use ribbon please config every server.
    #springCloud-test:
    #  ribbon:
    #    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

    eureka:
      client:
        enabled: true
        serviceUrl:
          defaultZone: http://shenyu-examples-eureka:8761/eureka/
      instance:
        prefer-ip-address: true

    management:
      health:
        redis:
          enabled: false
        elasticsearch:
          enabled: false
      endpoint:
        health:
          enabled: true
          show-details: always
      endpoints:
        web:
          exposure:
            include: "*" # or health,info

    shenyu:
      selectorMatchCache:
        ## selector L1 cache
        cache:
          enabled: false
          initialCapacity: 10000 # initial capacity in cache
          maximumSize: 10000 # max size in cache
        ## selector L2 cache, use trie as L2 cache
        trie:
          enabled: false
          cacheSize: 128 # the number of plug-ins
          matchMode: antPathMatch
      ruleMatchCache:
        ## rule L1 cache
        cache:
          enabled: true
          initialCapacity: 10000 # initial capacity in cache
          maximumSize: 65536 # max size in cache
        ## rule L2 cache, use trie as L2 cache
        trie:
          enabled: false
          cacheSize: 1024 # the number of selectors
          matchMode: antPathMatch
      netty:
        http:
          # set to false, user can custom the netty tcp server config.
          webServerFactoryEnabled: true
          selectCount: 1
          workerCount: 8
          accessLog: false
          serverSocketChannel:
            soRcvBuf: 87380
            soBackLog: 128
            soReuseAddr: false
            connectTimeoutMillis: 10000
            writeBufferHighWaterMark: 65536
            writeBufferLowWaterMark: 32768
            writeSpinCount: 16
            autoRead: false
            allocType: "pooled"
            messageSizeEstimator: 8
            singleEventExecutorPerGroup: true
          socketChannel:
            soKeepAlive: false
            soReuseAddr: false
            soLinger: -1
            tcpNoDelay: true
            soRcvBuf: 87380
            soSndBuf: 16384
            ipTos: 0
            allowHalfClosure: false
            connectTimeoutMillis: 10000
            writeBufferHighWaterMark: 65536
            writeBufferLowWaterMark: 32768
            writeSpinCount: 16
            autoRead: false
            allocType: "pooled"
            messageSizeEstimator: 8
            singleEventExecutorPerGroup: true
          sni:
            enabled: false
            mod: k8s #manul
            defaultK8sSecretNamespace: shenyu-ingress
            defaultK8sSecretName: default-cert
      #        mod: manual
      #        certificates:
      #          - domain: 'localhost'
      #            keyCertChainFile: '/Users/zhukunshuai/Desktop/cert/example.com+1.pem'
      #            keyFile: '/Users/zhukunshuai/Desktop/cert/example.com+1-key.pem'
      #          - domain: 'example.com'
      #            keyCertChainFile: '/Users/zhukunshuai/Desktop/cert/example.com+1.pem'
      #            keyFile: '/Users/zhukunshuai/Desktop/cert/example.com+1-key.pem'
      #  httpclient:
      #    strategy: webClient # netty
      #    connectTimeout: 45000
      #    responseTimeout: 3000
      #    readerIdleTime: 3000
      #    writerIdleTime: 3000
      #    allIdleTime: 3000
      #    readTimeout: 3000
      #    writeTimeout: 3000
      #    wiretap: false
      #    keepAlive: false
      #    maxInMemorySize: 1 #1mb
      #    pool:
      #      type: ELASTIC
      #      name: proxy
      #      maxConnections: 16
      #      acquireTimeout: 45000
      #      maxIdleTime: 3000
      #    proxy:
      #      host:
      #      port:
      #      username:
      #      password:
      #      nonProxyHostsPattern:
      #    ssl:
      #      useInsecureTrustManager: true
      #      keyStoreType: PKCS12
      #      keyStorePath: classpath:keystore.p12
      #      keyStorePassword: 123456
      #      keyStoreProvider:
      #      keyPassword: 123456
      #      trustedX509Certificates:
      #      handshakeTimeout:
      #      closeNotifyFlushTimeout:
      #      closeNotifyReadTimeout:
      #      defaultConfigurationType:
      #    threadPool:
      #      prefix: shenyu
      #      selectCount: 1
      #      workerCount: 8
      #      daemon: true
      register:
        enabled: false
        registerType: zookeeper #etcd #consul
        serverLists: localhost:2181 #http://localhost:2379 #localhost:8848
        props:
      cross:
        enabled: true
        allowedHeaders:
        allowedMethods: "*"
        allowedAnyOrigin: true # the same of Access-Control-Allow-Origin: "*"
          #    allowedOrigin:
        # format : schema://prefix spacer domain
        # Access-Control-Allow-Origin: "http://a.apache.org,http://b.apache.org"
        #      spacer: "."
        #      domain: apache.org
        #      prefixes:
        #        - a # a.apache.org
        #        - b # b.apache.org
        #      origins:
        #        - c.apache.org
        #        - d.apache.org
        #        - http://e.apache.org
        #      originRegex: ^http(|s)://(.*\.|)abc.com$
        allowedExpose: ""
        maxAge: "18000"
        allowCredentials: true

      switchConfig:
        local: true
        collapseSlashes: false
      file:
        enabled: true
        maxSize: 10
      exclude:
        enabled: false
        paths:
          - /favicon.ico
      fallback:
        enabled: false
        paths:
          - /fallback/hystrix
          - /fallback/resilience4j
          - /fallback/sentinel
      health:
        enabled: true
        paths:
          - /actuator
          - /health_check
      alert:
        enabled: true
        reportUrl: http://localhost:9095/alert/report
      extPlugin:
        path:
        enabled: true
        threads: 1
        scheduleTime: 300
        scheduleDelay: 30
      scheduler:
        enabled: false
        type: fixed
        threads: 16
      upstreamCheck:
        enabled: false
        poolSize: 10
        timeout: 3000
        healthyThreshold: 1
        unhealthyThreshold: 1
        interval: 5000
        printEnabled: true
        printInterval: 60000
      springCloudCache:
        enabled: false
      ribbon:
        serverListRefreshInterval: 10000
      metrics:
        enabled: false
        name: prometheus
        host: 127.0.0.1
        port: 8090
        jmxConfig:
        props:
          jvm_enabled: true
      #  plugins:
      #    rate-limiter.enabled: false
      local:
        enabled: false
        sha512Key: "BA3253876AED6BC22D4A6FF53D8406C6AD864195ED144AB5C87621B6C233B548BAEAE6956DF346EC8C17F5EA10F35EE3CBC514797ED7DDD3145464E2A0BAB413"
      websocket:
        enableProxyPing: false

    logging:
      level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.apache.shenyu.bonuspoint: info
        org.apache.shenyu.lottery: info
        org.apache.shenyu: info
        org.springframework.http.server.reactive: info
        org.springframework.web.reactive: info
        reactor.ipc.netty: info
        reactor.netty: info
        com.alibaba: debug

  application-admin-sync-websocket.yml: |
    shenyu:
      sync:
        websocket:
          enabled: true
          messageMaxSize: 10240
          allowOrigins: ws://localhost:9095;ws://localhost:9195;

  application-admin-sync-http.yml: |
    shenyu:
      sync:
        http:
          enabled: true

  application-admin-sync-zookeeper.yml: |
    shenyu:
      sync:
        zookeeper:
          url: shenyu-zookeeper:2181
          sessionTimeout: 5000
          connectionTimeout: 2000

  application-admin-sync-etcd.yml: |
    shenyu:
      sync:
        etcd:
          url: http://shenyu-etcd:2379

  application-admin-sync-nacos.yml: |
    shenyu:
      sync:
        nacos:
          url: shenyu-nacos.default.svc.cluster.local:8848
          namespace: 1c10d748-af86-43b9-8265-75f487d20c6c
          username:
          password:
          acm:
            enabled: false
            endpoint: acm.aliyun.com
            namespace:
            accessKey:
            secretKey:

  application-bootstrap-sync-websocket.yml: |
    shenyu:
      sync:
        websocket:
          urls: ws://shenyu-admin:9095/websocket
          allowOrigin: ws://localhost:9195

  application-bootstrap-sync-http.yml: |
    shenyu:
      sync:
        http:
          url: http://shenyu-admin:9095
          username: admin
          password: 123456
          enabled: true

  application-bootstrap-sync-zookeeper.yml: |
    shenyu:
      sync:
        zookeeper:
          url: shenyu-zookeeper:2181
          sessionTimeout: 5000
          connectionTimeout: 2000

  application-bootstrap-sync-etcd.yml: |
    shenyu:
      sync:
        etcd:
          url: http://shenyu-etcd:2379

  application-bootstrap-sync-nacos.yml: |
    shenyu:
      sync:
        nacos:
          url: shenyu-nacos.default.svc.cluster.local:8848
          namespace: 1c10d748-af86-43b9-8265-75f487d20c6c
          username:
          password:
          acm:
            enabled: false
            endpoint: acm.aliyun.com
            namespace:
            accessKey:
            secretKey:
