# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server:
  port: 9195
  address: 0.0.0.0

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: shenyu-bootstrap
#   cloud:
#    nacos:
#       discovery:
#          server-addr: 127.0.0.1:8848

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://shenyu-examples-eureka:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  health:
    defaults:
      enabled: false

shenyu:
  switchConfig:
    local: true
  cross:
    enabled: true
  sync:
    websocket:
      urls: ws://localhost:9095/websocket
      allowOrigin: ws://localhost:9195
  exclude:
    enabled: true
    paths:
      - /favicon.ico
      - /actuator/health
  local:
    enabled: true
    sha512Key: "BA3253876AED6BC22D4A6FF53D8406C6AD864195ED144AB5C87621B6C233B548BAEAE6956DF346EC8C17F5EA10F35EE3CBC514797ED7DDD3145464E2A0BAB413"

logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    org.apache.shenyu.bonuspoint: info
    org.apache.shenyu.lottery: info
    org.apache.shenyu: info

