### shengyu getway proxy orderSave
POST http://localhost:9195/http/order/save
Accept: application/json
Content-Type: application/json

{
  "id": 123,
  "name": "order"
}
### shengyu getway proxy orderSave
GET http://localhost:9195/http/order/findById?id=123
Accept: application/json
Content-Type: application/json

### shengyu getway proxy path
GET http://localhost:9195/http/order/path/123/hahah
Accept: application/json
Content-Type: application/json

### shengyu getway proxy path
GET http://localhost:9195/http/order/path/123/name
Accept: application/json
Content-Type: application/json

### shengyu getway proxy oauth2
GET http://localhost:9195/http/order/oauth2/test
Accept: application/json
Content-Type: application/json
Authorization:AuthorizationContext

### shengyu getway proxy payment
POST http://localhost:9195/http/test/payment
Accept: application/json
Content-Type: application/json

{
  "userId": 123,
  "userName": "name"
}
### shengyu getway proxy findByUserId
GET http://localhost:9195/http/test/findByUserId?userId=123
Accept: application/json
Content-Type: application/json

### shengyu getway proxy path
GET http://localhost:9195/http/test/path/123?name=haha
Accept: application/json
Content-Type: application/json

### shengyu getway proxy path
GET http://localhost:9195/http/test/path/123/name
Accept: application/json
Content-Type: application/json

### shengyu getway proxy waf pass
POST http://localhost:9195/http/test/waf/pass
Accept: application/json
Content-Type: application/json

### shengyu getway proxy waf deny
POST http://localhost:9195/http/test/waf/deny
Accept: application/json
Content-Type: application/json

### shengyu getway proxy request parameter pass
GET http://localhost:9195/http/test/request/parameter/pass?requestParameter=test
Accept: application/json
Content-Type: application/json
