// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package org.dromara.soul.examples.tars.servant.testapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface HelloServant {

	 String hello(@TarsMethodParameter(name="no")int no, @TarsMethodParameter(name="name")String name);

	 Integer helloInt(@TarsMethodParameter(name="no")int no, @TarsMethodParameter(name="name")String name);
}
