#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


### shengyu getway proxy echo
POST http://localhost:9195/grpc/echo
Accept: application/json
Content-Type: application/json

{
  "data": [
    {
      "message": "hello grpc"
    }
  ]
}

### create the file grpc-test-api.http under src/main/http/
### shengyu getway proxy unaryFun
POST http://localhost:9195/grpc/unaryFun
Accept: application/json
Content-Type: application/json

{
  "data": [
    {
      "message": "hello grpc"
    }
  ]
}
### shengyu getway proxy bidiStreamingFun
POST http://localhost:9195/grpc/bidiStreamingFun
Accept: application/json
Content-Type: application/json

{
  "data": [
    {
      "message": "hello grpc"
    }
  ]
}
### shengyu getway proxy bidiStreamingFun
POST http://localhost:9195/grpc/serverStreamingFun
Accept: application/json
Content-Type: application/json

{
  "data": [
    {
      "message": "hello grpc"
    },
    {
      "message": "hello grpc"
    }
  ]
}

### shengyu getway proxy clientStreamingFun
POST http://localhost:9195/grpc/serverStreamingFun
Accept: application/json
Content-Type: application/json

{
  "data": [
    {
      "message": "hello grpc"
    },
    {
      "message": "hello grpc"
    }
  ]
}
