#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# if you debug api, replace your own token

### selector list by page
GET http://localhost:9095/data-permission/selector/?currentPage=1&pageSize=10&userId=1&pluginId=1
Accept: application/json
Content-Type: application/json
X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiZXhwIjoxNjQ2ODMyOTc4fQ.-buYR6pt8ZwahRP90ArThvrSzd8_OAiNmGxi2iyFSRg

### rules list by page
GET http://localhost:9095/data-permission/rules/?currentPage=1&pageSize=10&userId=1&selectorId=1
Accept: application/json
Content-Type: application/json
X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiZXhwIjoxNjQ2ODMyOTc4fQ.-buYR6pt8ZwahRP90ArThvrSzd8_OAiNmGxi2iyFSRg

### selector add
POST http://localhost:9095/data-permission/selector
Accept: application/json
Content-Type: application/json
X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiZXhwIjoxNjQ2ODMyOTc4fQ.-buYR6pt8ZwahRP90ArThvrSzd8_OAiNmGxi2iyFSRg

{
  "userId": 1,
  "dataId": 1
}

### selector delete
DELETE http://localhost:9095/data-permission/selector
Accept: application/json
Content-Type: application/json
X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiZXhwIjoxNjQ2ODMyOTc4fQ.-buYR6pt8ZwahRP90ArThvrSzd8_OAiNmGxi2iyFSRg

{
  "userId": 1,
  "dataId": 1
}

### selector add
POST http://localhost:9095/data-permission/rule
Accept: application/json
Content-Type: application/json
X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiZXhwIjoxNjQ2ODMyOTc4fQ.-buYR6pt8ZwahRP90ArThvrSzd8_OAiNmGxi2iyFSRg

{
  "userId": 1,
  "dataId": 1
}

### selector delete
DELETE http://localhost:9095/data-permission/rule
Accept: application/json
Content-Type: application/json
X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiZXhwIjoxNjQ2ODMyOTc4fQ.-buYR6pt8ZwahRP90ArThvrSzd8_OAiNmGxi2iyFSRg

{
  "userId": 1,
  "dataId": 1
}
