#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Use gateway proxy
# if you used IDEA, start example project. click green button.Quick access！

### shengyu https example
GET https://localhost:8190/order/findById?id=3
Accept: application/json
Content-Type: application/json


### shengyu https upload file example
POST https://localhost:8190/upload/file
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.txt";
Content-Type: multipart/form-data

< ../../../../shenyu-examples-common/src/main/resources/1.txt
--WebAppBoundary--
